jbt_job_index:
    path:     /
    defaults: { _controller: "JbtKevinBoussardBundle:Job:index" }
    methods:  GET

jbt_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "JbtKevinBoussardBundle:Job:show" }
    methods:  GET
    requirements:
        id:  \d+

jbt_job_preview:
    pattern:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "JbtKevinBoussardBundle:Job:preview" }
    requirements:
        token:  \w+

jbt_job_new:
    path:     /new
    defaults: { _controller: "JbtKevinBoussardBundle:Job:new" }
    methods:  [GET, POST]

jbt_job_edit:
    path:     /{token}/edit
    defaults: { _controller: "JbtKevinBoussardBundle:Job:edit" }
    methods:  [GET, POST]

jbt_job_delete:
    path:     /{token}/delete
    defaults: { _controller: "JbtKevinBoussardBundle:Job:delete" }
    methods:  POST

jbt_job_publish:
    pattern:  /{token}/publish
    defaults: { _controller: "JbtKevinBoussardBundle:Job:publish" }
    methods:  [POST]