# src/Jbt/KevinBoussardBundle/Resources/config/doctrine/Category.orm.yml
Jbt\KevinBoussardBundle\Entity\Category:
  type: entity
  repositoryClass: Jbt\KevinBoussardBundle\Repository\CategoryRepository
  table: category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    slug:
      type: string
      length: 255
      unique: true
  oneToMany:
    jobs:
      targetEntity: Job
      mappedBy: category
    category_affiliates:
      targetEntity: CategoryAffiliate
      mappedBy: category
  lifecycleCallbacks:
    prePersist: [ setSlugValueOnPrePersist ]
    preUpdate: [ setSlugValueOnPreUpdate ]