# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.job:
        class: Jbt\KevinBoussardBundle\Admin\JobAdmin
        arguments: [~, Jbt\KevinBoussardBundle\Entity\Job, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Job }
    admin.category:
        class: Jbt\KevinBoussardBundle\Admin\CategoryAdmin
        arguments: [~, Jbt\KevinBoussardBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }