# src/Jbt/KevinBoussardBundle/Resources/config/routing.yml
JbtKevinBoussardBundle_job:
    resource: "@JbtKevinBoussardBundle/Resources/config/routing/job.yml"
    prefix: /job

JbtKevinBoussardBundle_category:
    resource: "@JbtKevinBoussardBundle/Resources/config/routing/category.yml"
    prefix: /category

JbtKevinBoussardBundle_search:
    resource: "@JbtKevinBoussardBundle/Resources/config/routing/search.yml"
    prefix: /search

JbtKevinBoussardBundle_ajax:
    resource: "@JbtKevinBoussardBundle/Resources/config/routing/ajax.yml"
    prefix: /api

JbtKevinBoussardBundle_homepage:
    pattern:  /
    defaults: { _controller: JbtKevinBoussardBundle:Job:index }

# Authentification
login:
    pattern:   /login
    defaults:  { _controller: JbtKevinBoussardBundle:Security:login }
logout:
    pattern:   /logout
