# src/Jbt/KevinBoussardBundle/Resources/config/routing.yml
JbtKevinBoussardBundle_job:
    resource: "@JbtKevinBoussardBundle/Resources/config/routing/job.yml"
    prefix: /job

JbtKevinBoussardBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JbtKevinBoussardBundle:Default:index }